### ISSUE TITLE
La función sumaUnoSiEsMismoTipo tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#1]
Básicamente, está haciendo dos cosas. Idealmente, cada función debería tener una única responsabilidad.
En este caso, podrías definir dos funciones diferentes, y combinarlas...

**Comment by fidel-ml** [comment]
NO debés cerrar los issues, sino responderlos. YO cierro los issues cuando el problema fue solucionado

**Comment by HectorVillavicencio** [comment]
Ahí lo corregí

**Comment by fidel-ml** [comment]
Yo la veo prácticamente igual... Sigue teniendo demasiadas responsabilidades. Tenés que dividirla en subtareas y usar esas subtareas (lo que vuelve innecesaria a la función).

**Comment by HectorVillavicencio** [comment]
Ahi esta

**Comment by fidel-ml** [comment]
Ahora que se expresa con otras subtareas, podrías eliminarla. De paso, su nombre no es adecuado, pues esa función no suma...
