### ISSUE TITLE
Pr2: `cuentaRegresiva` no es correcta

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#11]
¿La probaste? Para el caso 2, devolvés [2,1,1]...
Y además falla para los negativos, pero el enunciado pide otra cosa.

**Comment by HectorVillavicencio** [comment]
Lo corregí y use una subfunción cuentaRegresiva'

**Comment by fidel-ml** [comment]
Los nombres con ' no son demasiado felices... Tratá de encontrar nombres más adecuados.
