### ISSUE TITLE
Pr2: ¿por qué mirar la lista en el 1er caso de `losPrimeros`?

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#12]
Eso. Es innecesario que la mires... Y al hacerlo, muestra que seguís tratando de pensar en ambos parámetros al mismo tiempo. 
SIEMPRE pensá primero en uno y SOLAMENTE mirás el otro si hace falta (que en este caso, no).

**Comment by HectorVillavicencio** [comment]
Lo corregí, ahora solo mira una sola
