### ISSUE TITLE
Pr2: en `sinLosPrimeros`, el `else` del 2do caso se puede hacer mucho más fácil y eficiente

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#13]
Si el número NO es mayor que cero, ¿por qué seguir decrementándolo? Básicamente, al hacerlo va a seguir siendo menor a cero, y vas a entrar SIEMPRE por el else. Esto se podría escribir de forma más feliz...

**Comment by HectorVillavicencio** [comment]
Lo corregí y use una subfunción
