### ISSUE TITLE
Pr2: en `losQueLeGanan` estás dependiendo de la forma de calcular cuándo un Pokémon le gana a otro

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#15]
Básicamente, estás haciendo que esa función dependa del significado de ganar. Si luego lo queremos cambiar para que los Pokémon peleen más allá de su tipo (por ejemplo, por nivel), entonces esta función deja de andar. Siempre es bueno que las responsabilidades queden acotadas a las funciones que les corresponden. En este caso, contar cuántos ganan es cuestión de contar, y no de saber cómo pelean. Deberías utilizar una función que dados 2 Pokémon diga cuál gana...

**Comment by HectorVillavicencio** [comment]
Ahora puse una subtarea que solo deja los pokemons de un tipo especifico del entrenador 1 y esa lista pelea con la otra lista de pokemon del entrenador 2, y si un pokemon del entrenador 1 le gana a todos los pokemons del entrenador 2, suma un punto y así con todos los pokemons hasta terminar la lista.
