### ISSUE TITLE
Pr2: las funciones `tieneTipoAgua`, `tieneTipoFuego` y `tieneTipoPlanta` son prácticamente idénticas

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#16]
Se podrían generalizar, utilizando parámetros. Este tema es de Intro, y sería importante que lo recuerdes, porque así trabajás mucho de más (y es uno de los factores que hacen que en un parcial te quedes sin tiempo...)

**Comment by HectorVillavicencio** [comment]
Los reemplace por una única función que se llama "tieneTipo"
