### ISSUE TITLE
La función sinElPrimero es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#2]
En particular, no se puede quitar el primero de una lista sin elementos, por lo que debería fallar. Pero no lo hace...

**Comment by fidel-ml** [comment]
NO debés cerrar los issues, sino responderlos. YO cierro los issues cuando el problema fue solucionado

**Comment by HectorVillavicencio** [comment]
Ahí lo corregi
