### ISSUE TITLE
Pr2: en la función `asignadosPorProyecto` estás repitiendo muchas veces cada proyecto...

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#20]
O sea, si un proyecto `p` particular aparece 3 veces, ponés 3 elementos `(p,3)` en la lista final, y esto no es feliz.
Además, estás recorriendo muchísimas veces todos los proyectos de la empresa, lo que no es muy bueno.
La idea es usar recursión estructural sobre los proyectos de la empresa...

**Comment by HectorVillavicencio** [comment]
rehice todo el ejercicio

**Comment by fidel-ml** [comment]
Ahora recorre la empresa muchas veces. Si usás recursión estructural en lugar de 400 subtareas, sale con mucho menos esfuerzo...

**Comment by HectorVillavicencio** [comment]
Ahora creo que lo recorre menos veces

**Comment by fidel-ml** [comment]
Muchísimo mejor... Pero estás contando una persona menos, porque si hay uno solo trabajando, vos me decís que hay 0... :(

**Comment by HectorVillavicencio** [comment]
cambie el 0 por el 1
