### ISSUE TITLE
Pr3: `ponerN` realiza preguntas innecesarias a cada paso

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#23]
Dado que el else llama a exactamente lo mismo, si el número es menor que cero, se cuelga. Pero si no preguntás nada, también se cuelga, con lo cual la pregunta es innecesaria.
Si querés controlar para que en negativo no falle, deberías hacer algo como lo que explicamos ayer en clase para `cuentaRegresiva`: un wrapper...

**Comment by HectorVillavicencio** [comment]
lo corregí con un wrapper

**Comment by fidel-ml** [comment]
No está mal. El nombre `ponerSi` es inadecuado, porque no describe el propósito. Pero dado que usaste bien el wrapper, lo voy a dar por cerrado (igual, corregilo)
