### ISSUE TITLE
Pr1: la función `vieneDespues` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#4]
Primero, que la entendiste al revés: `Martes` viene después que `Lunes`, pero vos devolvés justo lo contrario.

Por otra parte, `Miercoles` viene después que `Lunes`, pero tu función (suponiendo que la invertimos), no lo indica adecuadamente, porque solamente considera el caso inmediato siguiente, y no todos.

Atención al corregirla de no caer en una explosión combinatoria de casos. El consejo es usar subtareas adecuadas.

**Comment by HectorVillavicencio** [comment]
Ahí lo corregi
