### ISSUE TITLE
Pr2: `agregar` NO está hecha por recursión estructural (y tiene casos de más para cómo está hecha)

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#7]
Esta es una práctica de recursión estructural. Agregar ES la misma función que `(++)`, pero la idea es hacerla desde cero, SIN utilizar esa función. 
Por otra parte, si vas a usar `(++)` para definir `agregar`, ¿cuál es la necesidad de mirar los dos primeros casos? Ya están contemplados en la subtarea `(++)`.
Y por si fuera poco, estás mirando los DOS parámetros, cuando dejamos en claro que esto SOLAMENTE debe hacerse cuando es imprescindible...
Tenés que tratar de aprender de los errores pasados y no repetirlos, porque si no se te va a hacer difícil en las próximas prácticas...

**Comment by HectorVillavicencio** [comment]
Lo corregi
