### ISSUE TITLE
Pr2: faltan casos en `zipMaximos`

### ISSUE THREAD

**Issue by fidel-ml** [HectorVillavicencio/EstrD22s1#8]
Estás controlando solamente listas de igual longitud, ya que en lugar de hacer una recursión sobre la primera, y solamente mirar la segunda cuando es necesario, estás haciendo recursión sobre AMBOS parámetros al mismo tiempo. 
NO TRABAJAMOS sCASI NUNCA obre los dos parámetros en simultáneo salvo contadísimas excepciones (que lo justifiquen).

**Comment by HectorVillavicencio** [comment]
Lo corregi
